### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapper
  - azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapperException
  fullName: azure.mgmt.machinelearningcompute.models.error_response_wrapper
  langs:
  - python
  module: azure.mgmt.machinelearningcompute.models.error_response_wrapper
  name: error_response_wrapper
  source:
    id: error_response_wrapper
    path: azure-mgmt-machinelearningcompute\azure\mgmt\machinelearningcompute\models\error_response_wrapper.py
    remote:
      branch: master
      path: azure-mgmt-machinelearningcompute\azure\mgmt\machinelearningcompute\models\error_response_wrapper.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.machinelearningcompute.models.error_response_wrapper
references:
- fullName: azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapper
  isExternal: false
  name: ErrorResponseWrapper
  parent: azure.mgmt.machinelearningcompute.models.error_response_wrapper
  uid: azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapper
- fullName: azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapperException
  isExternal: false
  name: ErrorResponseWrapperException
  parent: azure.mgmt.machinelearningcompute.models.error_response_wrapper
  uid: azure.mgmt.machinelearningcompute.models.error_response_wrapper.ErrorResponseWrapperException
