### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.keyvault.v2016_10_01.models.error.Error
  fullName: azure.keyvault.v2016_10_01.models.error
  langs:
  - python
  module: azure.keyvault.v2016_10_01.models.error
  name: error
  source:
    id: error
    path: azure-keyvault\azure\keyvault\v2016_10_01\models\error.py
    remote:
      branch: master
      path: azure-keyvault\azure\keyvault\v2016_10_01\models\error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.keyvault.v2016_10_01.models.error
references:
- fullName: azure.keyvault.v2016_10_01.models.error.Error
  isExternal: false
  name: Error
  parent: azure.keyvault.v2016_10_01.models.error
  uid: azure.keyvault.v2016_10_01.models.error.Error
