### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resourcegraph.models.facet_error.FacetError
  fullName: azure.mgmt.resourcegraph.models.facet_error
  langs:
  - python
  module: azure.mgmt.resourcegraph.models.facet_error
  name: facet_error
  source:
    id: facet_error
    path: azure-mgmt-resourcegraph\azure\mgmt\resourcegraph\models\facet_error.py
    remote:
      branch: master
      path: azure-mgmt-resourcegraph\azure\mgmt\resourcegraph\models\facet_error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resourcegraph.models.facet_error
references:
- fullName: azure.mgmt.resourcegraph.models.facet_error.FacetError
  isExternal: false
  name: FacetError
  parent: azure.mgmt.resourcegraph.models.facet_error
  uid: azure.mgmt.resourcegraph.models.facet_error.FacetError
