### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionError
  - azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionErrorException
  fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error
  langs:
  - python
  module: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error
  name: custom_vision_error
  source:
    id: custom_vision_error
    path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\custom_vision_error.py
    remote:
      branch: master
      path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\custom_vision_error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error
references:
- fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionError
  isExternal: false
  name: CustomVisionError
  parent: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionError
- fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionErrorException
  isExternal: false
  name: CustomVisionErrorException
  parent: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error.CustomVisionErrorException
