### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.models.auto_scale_run_error_py3.AutoScaleRunError
  fullName: azure.batch.models.auto_scale_run_error_py3
  langs:
  - python
  module: azure.batch.models.auto_scale_run_error_py3
  name: auto_scale_run_error_py3
  source:
    id: auto_scale_run_error_py3
    path: azure-batch\azure\batch\models\auto_scale_run_error_py3.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\auto_scale_run_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.batch.models.auto_scale_run_error_py3
references:
- fullName: azure.batch.models.auto_scale_run_error_py3.AutoScaleRunError
  isExternal: false
  name: AutoScaleRunError
  parent: azure.batch.models.auto_scale_run_error_py3
  uid: azure.batch.models.auto_scale_run_error_py3.AutoScaleRunError
